---
name: "Config"

on:
  workflow_call:
    inputs:
      platforms:
        description: "The platforms to build (CSV)"
        default: linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64,linux/ppc64le,linux/s390x
        required: false
        type: string
    outputs:
      go_version:
        description: "The go version"
        value: '1.19'
      image_name:
        description: "The Docker image name"
        value: cisagov/cyhy-commander
      data_artifact_name:
        description: "The name of the data artifact"
        value: data
      data_artifact_path:
        description: "The path to the data artifact directory"
        value: tests/config/commander_data_volume
      test_image_artifact_name:
        description: "The name of the test image artifact"
        value: test-image
      platforms:
        description: "The platforms to build (CSV)"
        value: ${{ inputs.platforms }}
      platforms_json:
        description: "The platforms to build (JSON)"
        value: ${{ jobs.csv-to-json.outputs.platforms_json }}
      python_version:
        description: "The Python version"
        value: '3.10'
      shfmt_version:
        description: "The shfmt version"
        value: v3.5.1

jobs:
  diagnostics:
    name: "Diagnostics"
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@2e205a28d0e1da00c5f53b161f4067b052c61f34
        with:  # TODO: change to 'egress-policy: block' after couple of runs
          egress-policy: audit

      - name: Check GitHub Status
        uses: crazy-max/ghaction-github-status@8d1f141b985510f36a0376b75b4dc8b0cfc90e8a
        with:
          overall_threshold: major
          packages_threshold: major_outage

      - name: Dump context
        uses: crazy-max/ghaction-dump-context@516dbb0c760f39b4cdd750ae095f1688780f68f4

  csv-to-json:
    name: "Convert platforms CSV to JSON"
    runs-on: ubuntu-latest
    outputs:
      platforms_json: ${{ steps.csv-to-json.outputs.platforms_json }}
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@2e205a28d0e1da00c5f53b161f4067b052c61f34
        with:  # TODO: change to 'egress-policy: block' after couple of runs
          egress-policy: audit

      - name: Convert CSV to JSON
        id: csv-to-json
        run: |
          echo "platforms_json=$(echo -n ${{ inputs.platforms }} | jq --raw-input --compact-output 'split(",")')" >> $GITHUB_OUTPUT
