---
name: "Build"

on:
  push:
    branches:
      - '**'
  pull_request:
  release:
    types:
      - edited
      - published
  schedule:
    - cron: '0 10 * * *'  # everyday at 10am
  workflow_dispatch:
    inputs:
      dispatch-tag:
        description: "Tag to apply to pushed images"
        required: true
        default: dispatch

permissions:
  actions: read
  contents: read

jobs:
  config:
    name: "Config"
    uses: ./.github/workflows/_config.yml

  metadata:
    name: "Metadata"
    needs:
      - config
    uses: ./.github/workflows/docker-metadata.yml
    with:
      image_name: ${{ needs.config.outputs.image_name }}

  docker-secrets:
    name: "Docker secrets"
    runs-on: ubuntu-latest
    steps:
      - name: Check docker.com credentials
        run: |
          return_code=0
          if [ -z "${{ secrets.DOCKER_USERNAME }}" ]; then
            echo "::warning::Set the DOCKER_USERNAME secret."
            return_code=1
          fi
          if [ -z "${{ secrets.DOCKER_PASSWORD }}" ]; then
            echo "::warning::Set the DOCKER_PASSWORD secret."
            return_code=1
          fi
          exit $return_code

  lint:
    name: "Lint"
    needs:
      - config
    uses: ./.github/workflows/common-lint.yml

  build-test-image:
    name: "Build test image"
    needs:
      - config
      - lint
      - metadata
    uses: ./.github/workflows/docker-build-image.yml
    with:
      artifact_name: ${{ needs.config.outputs.image_tarball_artifact_name }}
      cache_from_scopes: ${{ needs.config.outputs.test_platform }}
      cache_to_scope: ${{ needs.config.outputs.test_platform }}
      image_tarball_name: ${{ needs.config.outputs.test_platform }}.tar
      image_labels: ${{ needs.metadata.outputs.image_labels }}
      platforms: ${{ needs.config.outputs.test_platform }}
    secrets:
      build_args: |
        VERSION=${{ needs.metadata.outputs.source_version }}

  test-image:
    name: "Test image"
    needs:
      - build-test-image
      - config
    uses: ./.github/workflows/docker-pytest-image.yml
    with:
      data_artifact_name: ${{ needs.config.outputs.data_artifact_name }}
      data_artifact_path: ${{ needs.config.outputs.data_artifact_path }}
      image_artifact_name: ${{ needs.config.outputs.image_tarball_artifact_name }}
      image_tarball_name: ${{ needs.config.outputs.test_platform }}.tar

  build-each-platform:
    needs:
      - config
      - lint
      - metadata
      - test-image
    if: github.event_name != 'pull_request'
    strategy:
      matrix:
        platform: ${{ fromJson(needs.config.outputs.platforms_json) }}
        exclude:
          - platform: ${{ needs.config.outputs.test_platform }}
    name: "${{ matrix.platform }}"
    uses: ./.github/workflows/docker-build-image.yml
    with:
      artifact_name: ${{ needs.config.outputs.image_tarball_artifact_name }}
      cache_from_scopes: ${{ matrix.platform }}
      cache_to_scope: ${{ matrix.platform }}
      image_labels: ${{ needs.metadata.outputs.image_labels }}
      image_tarball_name: ${{ matrix.platform }}.tar
      platforms: ${{ matrix.platform }}
    secrets:
      build_args: |
        VERSION=${{ needs.metadata.outputs.source_version }}

  build-multi-arch-image:
    needs:
      - build-each-platform
      - config
      - docker-secrets
      - metadata
    if: github.event_name != 'pull_request'
    name: "Build and push multi-arch image"
    permissions:
      packages: write
    uses: ./.github/workflows/docker-multi-arch-push.yml
    with:
      artifact_name: ${{ needs.config.outputs.image_tarball_artifact_name }}
      image_tags: ${{ needs.metadata.outputs.image_tags }}
    secrets:
      docker_password: ${{ secrets.DOCKER_PASSWORD }}
      docker_username: ${{ secrets.DOCKER_USERNAME }}

  publish-readme:
    needs:
      - build-multi-arch-image
      - docker-secrets
    if: github.event_name == 'release' && !github.event.release.prerelease
    name: "Publish docs"
    uses: ./.github/workflows/docker-publish-description.yml
    with:
      image_name: ${{ needs.config.outputs.image_name }}
    secrets:
      docker_password: ${{ secrets.DOCKER_PASSWORD }}
      docker_username: ${{ secrets.DOCKER_USERNAME }}
