---

name: Build

on:
  push:
    branches:
      - '**'
  pull_request:
  release:
    types: [edited, published]
  schedule:
    - cron: '0 10 * * *'  # everyday at 10am
  workflow_dispatch:
    inputs:
      dispatch-tag:
        description: "Tag to apply to pushed images"
        required: true
        default: dispatch

permissions:
  actions: read
  contents: read

jobs:
  config:
    name: "Config"
    uses: ./.github/workflows/_config.yml

  metadata:
    name: "Metadata"
    needs: [config]
    uses: ./.github/workflows/_metadata.yml
    with:
      image_name: ${{ needs.config.outputs.image_name }}

  docker-secrets:
    name: "Docker secrets"
    runs-on: ubuntu-latest
    steps:
      - name: Check docker.com credentials
        run: |
          return_code=0
          if [ -z "${{ secrets.DOCKER_USERNAME }}" ]; then
            echo "::warning::Set the DOCKER_USERNAME secret."
            return_code=1
          fi
          if [ -z "${{ secrets.DOCKER_PASSWORD }}" ]; then
            echo "::warning::Set the DOCKER_PASSWORD secret."
            return_code=1
          fi
          exit $return_code

  lint:
    name: "Lint"
    needs: [config]
    uses: ./.github/workflows/_lint.yml
    with:
      go_version: ${{ needs.config.outputs.go_version }}
      python_version: ${{ needs.config.outputs.python_version }}
      shfmt_version: ${{ needs.config.outputs.shfmt_version }}

  build-normal-test-image:
    name: "Normal"
    needs: [config, metadata]
    uses: ./.github/workflows/_build-test-image.yml
    with:
      artifact_name: ${{ needs.config.outputs.normal_image_artifact_name }}
      image_labels: ${{ needs.metadata.outputs.image_labels }}
    secrets:
      build_args: |
        VERSION=${{ needs.metadata.outputs.source_version }}

  test-normal-image:
    name: "Normal"
    needs: [build-normal-test-image, config]
    uses: ./.github/workflows/_test-image.yml
    with:
      data_artifact_name: ${{ needs.config.outputs.normal_data_artifact_name }}
      image_artifact_name: ${{ needs.config.outputs.normal_image_artifact_name }}

  build-and-push:
    needs: [config, docker-secrets, lint, metadata, test-normal-image]
    if: github.event_name != 'pull_request'
    name: "Publish image"
    permissions:
      packages: write
    uses: ./.github/workflows/_build-push-all.yml
    with:
      build_args: |
        VERSION=${{ needs.metadata.outputs.source_version }}
      image_labels: ${{ needs.metadata.outputs.image_labels }}
      image_name: ${{ needs.config.outputs.image_name }}
      image_tags: ${{ needs.metadata.outputs.image_tags }}
      platforms: ${{ needs.config.outputs.platforms }}
    secrets:
      docker_password: ${{ secrets.DOCKER_PASSWORD }}
      docker_username: ${{ secrets.DOCKER_USERNAME }}

  publish-readme:
    needs: [build-and-push]
    if: github.event_name == 'release' && !github.event.release.prerelease
    name: "Publish docs"
    uses: ./.github/workflows/_publish-readme.yml
    with:
      image_name: ${{ needs.config.outputs.image_name }}
    secrets:
      docker_password: ${{ secrets.DOCKER_PASSWORD }}
      docker_username: ${{ secrets.DOCKER_USERNAME }}
