---
name: "Calculate Docker metadata"

# This reusable workflow calculates the labels and tags for a Docker image.
# These tags will vary depending on the event that triggered the workflow.

on:
  workflow_call:
    inputs:
      # Required inputs
      image_name:
        description: "The Docker image name"
        required: true
        type: string
    outputs:
      image_labels:
        description: "The calculated image labels"
        value: ${{ jobs.metadata.outputs.image_labels }}
      image_tags:
        description: "The calculated image tags"
        value: ${{ jobs.metadata.outputs.image_tags }}
      source_version:
        description: "The version declared in the source code"
        value: ${{ jobs.metadata.outputs.source_version }}

jobs:
  metadata:
    name: "Calculate variables"
    runs-on: ubuntu-latest
    outputs:
      image_labels: ${{ steps.docker_meta.outputs.labels }}
      image_tags: ${{ steps.docker_meta.outputs.tags }}
      source_version: ${{ steps.source_values.outputs.source_version }}
      tags: ${{ steps.prep.outputs.tags }}
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@2e205a28d0e1da00c5f53b161f4067b052c61f34
        with:
          # TODO: change to 'egress-policy: block' after couple of runs
          egress-policy: audit
      - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8

      - name: Calculate values from source
        id: source_values
        run: |
          echo "source_version=$(./bump_version.sh show)" >> $GITHUB_OUTPUT

      - name: Calculate Docker metadata
        id: docker_meta
        uses: docker/metadata-action@57396166ad8aefe6098280995947635806a0e6ea
        with:
          flavor: |
            latest=false
          images: |
            ${{ inputs.image_name }}
            ghcr.io/${{ inputs.image_name }}
          labels: |
            org.opencontainers.image.version=${{ steps.source_values.outputs.source_version }}
          tags: |
            type=edge
            type=raw,value=latest,enable=${{ github.event_name == 'release' && !github.event.release.prerelease }}
            type=raw,value=prerelease,enable=${{ github.event_name == 'release' && github.event.release.prerelease }}
            type=raw,value=release,enable=${{ github.event_name == 'release' && !github.event.release.prerelease }}
            type=raw,event=workflow_dispatch,value=${{ github.event.inputs.dispatch-tag }}
            type=ref,event=branch
            type=ref,event=pr
            type=schedule,pattern=nightly
            type=semver,pattern={{major}},enable=${{ github.event_name == 'release' && !github.event.release.prerelease }}
            type=semver,pattern={{major}}.{{minor}},enable=${{ github.event_name == 'release' && !github.event.release.prerelease }}
            type=semver,pattern={{version}},enable=${{ github.event_name == 'release' }}
            type=sha
